# Generated by Django 2.0.7 on 2022-04-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromCompany', models.CharField(max_length=46, null=True)),
                ('fromStreet1', models.CharField(max_length=46, null=True)),
                ('fromStreet2', models.CharField(max_length=46, null=True)),
                ('fromCity', models.CharField(max_length=46, null=True)),
                ('fromState', models.CharField(max_length=46, null=True)),
                ('fromZip', models.IntegerField(null=True)),
                ('fromPhone', models.IntegerField(null=True)),
                ('toName', models.CharField(max_length=46, null=True)),
                ('toCompany', models.CharField(max_length=46, null=True)),
                ('toStreet1', models.CharField(max_length=46, null=True)),
                ('toCity', models.CharField(max_length=46, null=True)),
                ('toState', models.CharField(max_length=46, null=True)),
                ('toZip', models.IntegerField(null=True)),
            ],
        ),
    ]
